name = "knull-trigger-auth"
main = "cloudflare/trigger-worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "knull-users"
database_id = "15a6141f-668b-4802-9607-e68be7a3a74c"

[vars]
TRIGGER_WS_URL = ""